version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo node version check
      - node -v
      - npm -v
      
  pre_build:
    commands:
      - npm install
      - npm install vite-plugin-proxy --save-dev
      - npm install --save-dev vite-plugin-proxy
      
      - npm install @aws-sdk/client-acm
      - npm install @aws-sdk/credential-provider-env
      - npm install @sveltejs/adapter-node
      - npm install express
      
  build:
    commands:
      - echo Build Starting on `date` 
      - npm run build
      - pwd 
      - ls -al

artifacts:
  files:
     - '**/*'
#  discard-path: no
#  base-directory: build