version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo node version check
      - node -v
      - npm -v
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building...
      - npm run build
      - echo Build Starting on `date` 
      - pwd 
      - ls -al

artifacts:
  files:
     - '**/*'
  discard-path: no
  base-directory: build