version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo node version check
      - node -v
      - npm -v
      
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - echo Build Starting on `date`
      - npm run build
      - pwd
      - ls -al

artifacts:
  files:
     - '**/*'
#  discard-path: no
#  base-directory: build